# Generated by Django 5.2.1 on 2025-06-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_menteeprofile_user_alter_mentorprofile_user'),
        ('mentor', '0002_task_title_alter_meetingrecording_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoravailability',
            name='mentee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.menteeprofile'),
        ),
    ]
