services:
  web:
    build: .
    container_name: matkamestre
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"