# Generated by Django 5.2.1 on 2025-06-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
