# Generated by Django 5.2.1 on 2025-06-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_menteeprofile_user_alter_mentorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/mentee/'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/mentor/'),
        ),
    ]
