# Generated by Django 5.2.1 on 2025-06-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_menteeprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
