# Generated by Django 5.2.1 on 2025-10-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_menteeprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menteeprofile',
            name='stage',
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='mentee_files/cv/', verbose_name='CV/Resume (PDF)'),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='language_proficiency',
            field=models.CharField(choices=[('en', 'English'), ('fi', 'Finnish'), ('sv', 'Swedish'), ('es', 'Spanish (Español)'), ('pt', 'Portuguese (Português)'), ('zh', 'Chinese (Mandarim)'), ('hi', 'Hindi'), ('ar', 'Arabic (العربية)'), ('fr', 'French (Français)'), ('ru', 'Russian (Русский)'), ('de', 'German (Deutsch)'), ('it', 'Italian (Italiano)'), ('ja', 'Japanese (日本語)'), ('ko', 'Korean (한국어)'), ('nl', 'Dutch (Nederlands)'), ('tr', 'Turkish (Türkçe)'), ('pl', 'Polish (Polski)'), ('cs', 'Czech (Čeština)'), ('uk', 'Ukrainian (Українська)'), ('fa', 'Farsi (Persian/Dari)'), ('tr', 'Turkish (Türkçe)'), ('so', 'Somali'), ('ar', 'Arabic')], default='en', help_text='Primary language for Mentoring/job search.', max_length=5),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Preferred working location (e.g., Helsinki, Tampere, Remote).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='professional_career_goal',
            field=models.TextField(blank=True, help_text='Summary of foreign experience, desired Finnish sector, and career goals.', null=True, verbose_name='Professional Background & Goals'),
        ),
    ]
