# Generated by Django 5.2.1 on 2025-10-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_menteeprofile_stage_menteeprofile_cv_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menteeprofile',
            old_name='language_proficiency',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='menteeprofile',
            name='professional_career_goal',
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='professional_career',
            field=models.TextField(blank=True, null=True, verbose_name='Professional Background'),
        ),
    ]
