# Generated by Django 5.2.1 on 2025-10-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_language_proficiency_menteeprofile_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='cv_analysis_feedback',
            field=models.TextField(blank=True, help_text="Initial feedback on the mentee's CV.", null=True, verbose_name='CV Analysis Feedback'),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='language',
            field=models.TextField(blank=True, help_text='Primary language for coaching/job search.', null=True),
        ),
    ]
