# Generated by Django 5.2.1 on 2025-10-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_menteeprofile_cv_analysis_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='professional_goal',
            field=models.TextField(blank=True, help_text='Describe your professional goals in Finland.', null=True, verbose_name='Professional Goal'),
        ),
    ]
