# Generated by Django 5.2.1 on 2025-10-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_menteeprofile_professional_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeprofile',
            name='cv_analysis_feedback',
            field=models.FileField(blank=True, help_text="Initial feedback on the mentee's CV, uploaded as a PDF.", null=True, upload_to='mentee_files/cv_analysis/', verbose_name='CV Analysis Feedback (PDF)'),
        ),
    ]
