# Generated by Django 5.2.1 on 2025-10-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_menteeprofile_cv_analysis_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='professional_career',
            field=models.TextField(blank=True, null=True, verbose_name='Professional Background'),
        ),
    ]
