# Generated by Django 5.2.1 on 2025-10-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_mentorprofile_professional_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='language',
            field=models.TextField(blank=True, help_text='Languages spoken for mentoring.', null=True),
        ),
    ]
